[build]
  publish = "public"
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
