[build]
  command = "cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/views/**/*", "netlify/functions/models/**/*"]
  external_node_modules = ["ejs", "bcryptjs", "mongoose"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
