[build]
  command = "cd netlify/functions && npm install && cd ../.."
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose", "serverless-http", "bcryptjs", "jsonwebtoken", "dotenv", "cors", "moment", "moment-timezone", "ejs"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
