[build]
  publish = "/"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/mitarbeiter/*"
  to = "/mitarbeiter/index.html"
  status = 200

[[redirects]]
  from = "/hausmeister/*"
  to = "/hausmeister/index.html"
  status = 200
