[build]
  command = "npm install && cd netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/views/**/*"]
  external_node_modules = ["express", "ejs"]
